export enum StatusOrdemServico {
  RASCUNHO = 'RASCUNHO',
  AGUARDANDO_APROVACAO = 'AGUARDANDO_APROVACAO',
  APROVADA = 'APROVADA',
  EM_EXECUCAO = 'EM_EXECUCAO',
  PAUSADA = 'PAUSADA',
  CONCLUIDA = 'CONCLUIDA',
  CANCELADA = 'CANCELADA',
  REJEITADA = 'REJEITADA'
}

export enum PrioridadeOS {
  BAIXA = 'BAIXA',
  MEDIA = 'MEDIA',
  ALTA = 'ALTA',
  URGENTE = 'URGENTE'
}

export enum TipoHistoricoOS {
  CRIACAO = 'CRIACAO',
  EDICAO = 'EDICAO',
  MUDANCA_STATUS = 'MUDANCA_STATUS',
  APROVACAO = 'APROVACAO',
  REJEICAO = 'REJEICAO',
  COMENTARIO = 'COMENTARIO',
  ANEXO = 'ANEXO',
  CHECKLIST = 'CHECKLIST'
}