# Configuração do Alertmanager para GarapaSystem
global:
  smtp_smarthost: 'smtp.garapasystem.com:587'
  smtp_from: 'alerts@garapasystem.com'
  smtp_auth_username: 'alerts@garapasystem.com'
  smtp_auth_password: '${SMTP_PASSWORD}'
  smtp_require_tls: true

# Templates para notificações
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Configuração de rotas
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'
  routes:
    # Alertas críticos - notificação imediata
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 5m

    # Alertas de instâncias específicas
    - match_re:
        alertname: 'InstanceDown|HighErrorRate|DatabaseConnectionFailed'
      receiver: 'instance-alerts'
      group_by: ['company_id', 'instance_id']

    # Alertas de infraestrutura
    - match_re:
        alertname: 'CollectorDown|PrometheusDown|ElasticsearchDown'
      receiver: 'infrastructure-alerts'

    # Alertas de segurança
    - match_re:
        alertname: 'UnauthorizedAccess|CertificateExpiring|TLSHandshakeFailed'
      receiver: 'security-alerts'

    # Alertas de performance
    - match_re:
        alertname: 'HighLatency|HighMemoryUsage|HighCPUUsage'
      receiver: 'performance-alerts'

# Configuração de receivers
receivers:
  - name: 'default'
    email_configs:
      - to: 'admin@garapasystem.com'
        subject: '[GarapaSystem] {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
          {{ end }}

  - name: 'critical-alerts'
    email_configs:
      - to: 'critical@garapasystem.com'
        subject: '[CRÍTICO] {{ .GroupLabels.alertname }} - {{ .GroupLabels.company_id }}'
        body: |
          🚨 ALERTA CRÍTICO 🚨
          
          {{ range .Alerts }}
          Empresa: {{ .Labels.company_id }}
          Instância: {{ .Labels.instance_id }}
          Serviço: {{ .Labels.service }}
          
          Problema: {{ .Annotations.summary }}
          Descrição: {{ .Annotations.description }}
          
          Horário: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
          
          Dashboard: https://telemetry.garapasystem.com/grafana/d/instance-overview?var-company={{ .Labels.company_id }}&var-instance={{ .Labels.instance_id }}
          {{ end }}
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#alerts-critical'
        title: '🚨 Alerta Crítico - {{ .GroupLabels.company_id }}'
        text: |
          {{ range .Alerts }}
          *Empresa:* {{ .Labels.company_id }}
          *Instância:* {{ .Labels.instance_id }}
          *Problema:* {{ .Annotations.summary }}
          *Descrição:* {{ .Annotations.description }}
          {{ end }}

  - name: 'instance-alerts'
    email_configs:
      - to: 'instances@garapasystem.com'
        subject: '[Instância] {{ .GroupLabels.company_id }} - {{ .GroupLabels.alertname }}'
        body: |
          Alerta de Instância
          
          {{ range .Alerts }}
          Empresa: {{ .Labels.company_id }}
          Instância: {{ .Labels.instance_id }}
          Versão: {{ .Labels.service_version }}
          
          Problema: {{ .Annotations.summary }}
          Descrição: {{ .Annotations.description }}
          
          Runbook: {{ .Annotations.runbook_url }}
          Dashboard: https://telemetry.garapasystem.com/grafana/d/instance-overview?var-company={{ .Labels.company_id }}
          {{ end }}

  - name: 'infrastructure-alerts'
    email_configs:
      - to: 'infra@garapasystem.com'
        subject: '[Infraestrutura] {{ .GroupLabels.alertname }}'
        body: |
          Alerta de Infraestrutura
          
          {{ range .Alerts }}
          Componente: {{ .Labels.job }}
          Instância: {{ .Labels.instance }}
          
          Problema: {{ .Annotations.summary }}
          Descrição: {{ .Annotations.description }}
          
          Ação Recomendada: {{ .Annotations.action }}
          {{ end }}
    pagerduty_configs:
      - routing_key: '${PAGERDUTY_ROUTING_KEY}'
        description: '{{ .GroupLabels.alertname }} - {{ .GroupLabels.job }}'

  - name: 'security-alerts'
    email_configs:
      - to: 'security@garapasystem.com'
        subject: '[SEGURANÇA] {{ .GroupLabels.alertname }}'
        body: |
          🔒 ALERTA DE SEGURANÇA 🔒
          
          {{ range .Alerts }}
          Tipo: {{ .Labels.alertname }}
          Origem: {{ .Labels.instance }}
          
          Detalhes: {{ .Annotations.description }}
          
          Ação Imediata Necessária: {{ .Annotations.action }}
          {{ end }}
    slack_configs:
      - api_url: '${SLACK_WEBHOOK_URL}'
        channel: '#security-alerts'
        title: '🔒 Alerta de Segurança'

  - name: 'performance-alerts'
    email_configs:
      - to: 'performance@garapasystem.com'
        subject: '[Performance] {{ .GroupLabels.alertname }} - {{ .GroupLabels.company_id }}'
        body: |
          Alerta de Performance
          
          {{ range .Alerts }}
          Empresa: {{ .Labels.company_id }}
          Serviço: {{ .Labels.service }}
          Métrica: {{ .Labels.alertname }}
          
          Valor Atual: {{ .Annotations.current_value }}
          Threshold: {{ .Annotations.threshold }}
          
          Recomendação: {{ .Annotations.recommendation }}
          {{ end }}

# Configuração de inibição (evitar spam de alertas)
inhibit_rules:
  # Se uma instância está down, não alertar sobre métricas específicas
  - source_match:
      alertname: 'InstanceDown'
    target_match_re:
      alertname: 'HighLatency|HighErrorRate|DatabaseConnectionFailed'
    equal: ['company_id', 'instance_id']

  # Se o coletor está down, não alertar sobre falta de métricas
  - source_match:
      alertname: 'CollectorDown'
    target_match_re:
      alertname: 'MetricsNotReceived|TracesNotReceived'
    equal: ['cluster']

# Configuração de silenciamento automático
mute_time_intervals:
  - name: 'maintenance-window'
    time_intervals:
      - times:
          - start_time: '02:00'
            end_time: '04:00'
        weekdays: ['sunday']
        months: ['1:12']

  - name: 'business-hours'
    time_intervals:
      - times:
          - start_time: '09:00'
            end_time: '18:00'
        weekdays: ['monday:friday']