# Configuração do Prometheus para GarapaSystem
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'garapasystem-central'
    environment: 'production'

# Configuração de regras de alerta
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Configuração do Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Configuração de scraping
scrape_configs:
  # Métricas do próprio Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Métricas do coletor OpenTelemetry
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # Métricas exportadas pelo coletor (das instâncias)
  - job_name: 'garapasystem-instances'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 30s
    metrics_path: '/metrics'
    honor_labels: true

  # Métricas do Jaeger
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
    scrape_interval: 30s

  # Métricas do Elasticsearch
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    scrape_interval: 30s
    metrics_path: '/_prometheus/metrics'

  # Métricas do Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Métricas do sistema (node_exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Descoberta automática de instâncias GarapaSystem
  - job_name: 'garapasystem-discovery'
    consul_sd_configs:
      - server: 'consul:8500'
        services: ['garapasystem']
    relabel_configs:
      - source_labels: [__meta_consul_service_metadata_company_id]
        target_label: company_id
      - source_labels: [__meta_consul_service_metadata_instance_id]
        target_label: instance_id
      - source_labels: [__meta_consul_service_metadata_version]
        target_label: service_version
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Métricas de instâncias específicas (configuração estática)
  - job_name: 'garapasystem-static'
    static_configs:
      - targets: []  # Será preenchido dinamicamente
    scrape_interval: 30s
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.+):(\d+)'
        target_label: __address__
        replacement: '${1}:9090'  # Porta padrão do Prometheus exporter

# Configuração de armazenamento remoto (opcional)
remote_write:
  - url: "https://prometheus-remote.garapasystem.com/api/v1/write"
    basic_auth:
      username: "${REMOTE_WRITE_USERNAME}"
      password: "${REMOTE_WRITE_PASSWORD}"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500

remote_read:
  - url: "https://prometheus-remote.garapasystem.com/api/v1/read"
    basic_auth:
      username: "${REMOTE_READ_USERNAME}"
      password: "${REMOTE_READ_PASSWORD}"