version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: garapasys_db
      POSTGRES_USER: garapasys_user
      POSTGRES_PASSWORD: garapasys_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./prisma/init-complete.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U garapasys_user -d garapasys_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: garapadev/garapasystem:0.1.32
    environment:
      DATABASE_URL: "postgresql://garapasys_user:garapasys_password@postgres:5432/garapasys_db?schema=public"
      NEXTAUTH_SECRET: "KmYl85qqhLFfe0VMH+k+bAelK+r1fWcGem+F+beJj+M="
      NEXTAUTH_URL: "http://localhost:3000"
      NODE_ENV: "production"
      PORT: "3000"
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local